# The URL the site will be built for
base_url = "https://d3rjust1n.xyz"

# Default Author
author = "D3rJust1n"

title = "D3rJust1n"
description = "Mein Blog"

# Generate a feed
generate_feeds = true

# Filename for the Feed
feed_filenames = ["rss.xml"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "linkita"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

[[taxonomies]]
name = "categories"
feed = true
paginate_by = 5

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 5

[[taxonomies]]
name = "authors"
feed = true
paginate_by = 5

[extra]
# Put all your custom variables here

mermaid = true

header_menu_name = "menu_name"

[extra.profiles.D3rJust1n]
name = "D3rJust1n"
avatar_url = "images/pb.png"
bio = "Mein Blog"

social = [
    { name = "instagram", url = "https://instagram.com/d3rjust1n" },
    { name = "tiktok", url = "https://tiktok.com/@d3rjust1nn" },
    { name = "youtube", url = "https://youtube.com/@d3rjust1n" },
    { name = "discord", url = "https://d3r.eu/dc" },
    { name = "twitch", url = "https://twitch.tv/d3rjust1nn" },
    { name = "bluesky", url = "https://bsky.app/profile/d3rjust1n.bsky.social" },
    { name = "anilist", url = "https://anilist.co/user/d3rjust1n" },
    { name = "github", url = "https://github.com/d3rjust1n" },
    { name = "codeberg", url = "https://codeberg.org/d3rjust1n" },
    { name = "rss", url = "$BASE_URL/rss.xml" }
]

[extra.menus]
menu_name = [
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/projekte", name = "Projekte"},
]

[extra.footer]
since = 2024
license_url = "/impressum"
copyright = "&copy; $YEAR D3rJust1n &vert; [Impressum]($LICENSE_URL)"